name: Deploy
on:
  push:
    branch:
      - main
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  
  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
          # path: |
          #  dist
          #  package.json
        
  Deploy:
    runs-on: ubuntu-latest
    needs: [Test, Build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Check artifacts
        run: ls
      - name: Deploy
        run: echo DEPLOYING...
